# Generated by Django 5.2 on 2025-04-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcode",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
