# Generated by Django 5.2 on 2025-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_emailcode_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Покупатель"),
                    ("seller", "Продавец"),
                    ("admin", "Админ"),
                ],
                default="buyer",
                max_length=20,
            ),
        ),
    ]
