# Generated by Django 5.2 on 2025-05-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_deliverymethod_paymentmethod_checkout_good_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.recipient"
            ),
        ),
    ]
