# Generated by Django 5.2 on 2025-06-02 20:17

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_checkout_is_paid_checkout_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="goods/",
            ),
        ),
    ]
