# Generated by Django 5.2 on 2025-06-02 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_goodimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="basketitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="basketitem",
            constraint=models.UniqueConstraint(
                fields=("user", "good"), name="unique_user_good"
            ),
        ),
    ]
